---
title: "Research"
---

## Publications

#### - "Human Rights in the United States." *(Forthcoming in PS: Political Science & Politics with K. Chad Clay & Meridith Lavelle)*

Part of a special issue for which the three of us are co-guest editors. In this introductory paper, we compare the United States' human rights performance across several human rights measurement projects and set the scene for the rest of the special issue.

------------------------------------------------------------------------

## Working papers

#### - "Cyber norm initiation in the international system." *(with Seden Akcinaroglu, Jeson Li, Alice Hong, & Yusuf Evirgen)*

We argue that although states have a shared interest in developing norms surrounding conduct in cyberspace, the different internal and external threats that they face lead them to have different ideas as to what these norms should be, preventing a consensus from being reached.

------------------------------------------------------------------------

## Dissertation

#### "Digital Frontlines: How Cyber Conflict Reshapes the Relationships Between States, Insurgents, and Citizens." *(working title)*

While the literature on cyber operations in international politics is growing, it is limited in breadth. This dissertation asks what the broader consequences of internet and computer-driven conflict — referred to as cyber conflict or cyber operations — are for not only how wars are fought, but for the relationships among conflict actors and civilian populations. Because cyber tools are now used by both states and armed non-state actors, their conseqeuences cannot be understood only through the lens of interstate conflict. Existing research has focused heavily on interstate cyber conflict, escalation, deterrence, and public responses to cyberattacks. Much less attention has been paid to how cyber operations reshape state-citizen relations, how cyber capabilities travel into the domain of armed non-state actors, and how these capabilites alter militant groups' relationships with civilians and adversaries through changes in their tactical repertoires. This dissertation fills that gap using novel large-N data on cyber operations and armed non-state actor behavior. It examines three related questions: First, how do states use cyber threats to justify new forms of digital repression? Second, under what conditions do militant groups adopt and use cyber capabilities? Third, how do cyber capabilities change militant groups' tactical repertoires, including whether cyber operations substitute for or complement physical violence against civilians?

As a whole, this dissertation aims to explore the ways in which cyber changes the relationship between conflict actors, be it those who are conducting operations, are affected by them, or both. It also provides, to my knowledge, the first discussions of the link between cyber conflict and digital repression and the first comprehensive evidence of militant groups’ development of cyber capabilities and use of cyber operations. Through the collection of novel data and rigorous empirical analysis, this dissertation contributes to the growing literature on the effects of cyber conflict in international politics. It also provides valuable insights for policymakers in the counterinsurgency realm, as well as for human rights defenders working in the areas of digital repression and civilian victimization in civil conflict. As a first cut at these topics, it is my hope that this dissertation also serves as a jumping off point for future cyber conflict research emphasizing its effects on civilians’ rights and safety and its use by violent non-state actors.

#### Chapter 1: *Digital damage control: Cyber conflict and its implications for domestic repression*

#### Chapter 2: *Opportunity, willingness, and the adoption of cyber capabilities by militant groups*

#### Chapter 3: *Armed and online: Cyber capabilities and insurgent violence*

