---
title: "Teaching"
---

### Binghamton University (SUNY)

#### Instructor of Record

-   PLSC 380C: Politics & Technology (Spring 2026) <br> [<i class="bi bi-eye"></i> View Syllabus](Lind_PoliticsTechnology_Syllabus_Spring2026.pdf){.btn .btn-outline-primary .btn-sm target="_blank" role="button"} [<i class="bi bi-download"></i> Download Syllabus](Lind_PoliticsTechnology_Syllabus_Spring2026.pdf){.btn .btn-outline-primary .btn-sm role="button"}

#### Teaching Assistant

-   PLSC/HMRT 100: Introduction to Human Rights (Spring 2025)

-   PLSC 111: Introduction to American Politics (Spring 2024)

-   PLSC 117: Introduction to World Politics (Fall 2023, Fall 2024)

------------------------------------------------------------------------

### University of Rhode Island

#### Graduate Teaching Assistant

-   PSC 310: Introduction to Political Science Research (Fall 2022, Spring 2023)

-   PSC 116: Introduction to International Politics (Spring 2023)

-   PSC 113: Introduction to American Politics (Fall 2022)

#### Undergraduate Teaching Assistant

-   JOR 110: Introduction to Mass Media (Fall 2021, Spring 2022)

-   PSC 310: Introduction to Political Science Research (Spring 2021)

#### Other

-   Writing Consultant, URI Undergraduate Writing Center
